rust: Don't fail 'make distclean' if cargo clean fails
It fails when run twice with:

  ../run cargo clean
  error: could not find `Cargo.toml` in `/home/rjones/d/libguestfs/rust` or any parent directory

As this is an optional step don't fail here.

(cherry picked from commit c7d54697ca8d83c7ad934026ee327816627d2444)